### ISSUE TITLE
Clear app log after each build

### ISSUE THREAD

**Issue by jor3l** [pebble/cloudpebble#122] opened 2015-01-27 23:20 UTC
Not sure if possible but I was going crazy with this, lots of info in the app log and was really hard to find something.

**Comment by kamotswind** [comment] 2015-07-24 14:00
If this is considered, please make it a configurable option, or a button to clear. I sometimes need the historical information in one screen to compare results of changes.

**Comment by Spacerat** [comment] 2015-10-06 15:49
This is essentially a duplicate of #100. #216 will add a button to clear the logs.

**Closed by Spacerat** 2015-10-06 15:49 UTC
