### ISSUE TITLE
Broken App Config

### ISSUE THREAD

**Issue by nhandler** [pebble/cloudpebble#137] opened 2015-04-28 21:34 UTC
I am trying to test my PebbleJS's ap config using cloud pebble. I followed the guide on the blog (http://developer.getpebble.com/blog/2015/01/22/cloudpebble-pebble-emulator/) to support the return_to query parameter. However, since cloud pebble appends #%7B%7D to my config URL (before the query string), the code snippet to get the return_to parameter is broken (you need to use location.hash.substring(8)).

Even with the above change (which allows my config to return properly to cloud pebble), it causes Settings.config() to believe that an error occured. I am unable to view any error message. I am also unable to access any of the saved form fields. This config works fine on the Pebble itself.

**Comment by Katharine** [comment] 2015-04-28 21:35
It's hard to tell without knowing what the URL is, but this looks like a duplicate of #124.

**Comment by nhandler** [comment] 2015-04-28 21:41
My URL is: https://somehostnamegoeshere.dev/config

There is no anchor in the URL. The URL cloud pebble attempts to open is: https://somehostnamegoeshere.dev/config#%7B%7D?return_to=https%3A//cloudpebble.net/ide/emulator/config%3F#%7B%7D

**Closed** 2015-04-28 21:44 UTC
