### ISSUE TITLE
Proposal : Button to clear log window

### ISSUE THREAD

**Issue by marcteys** [pebble/cloudpebble#187] opened 2015-07-26 20:44 UTC
Hi, After a while, all the logs are stacked and you always have to scroll to the bottom to see the last log. That's a waste of time. A button "clear log" would be perfect to avoid to refresh the page.

What do you think ?

**Comment by unwiredben** [comment] 2015-07-27 03:26
Duplicate of issue #100

**Closed** 2015-09-29 20:10 UTC
Labels: duplicate
